language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t ehermstad/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ehermstad/react-test npm test -- --coverage

after_success:
  - docker build -t ehermstad/multi-client ./client
  - docker build -t ehermstad/multi-nginx ./nginx
  - docker build -t ehermstad/multi-server ./server
  - docker build -t ehermstad/multi-worker ./worker
  #login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  #take images and push them to docker hub
  - docker push ehermstad/multi-client
  - docker push ehermstad/multi-nginx
  - docker push ehermstad/multi-server
  - docker push ehermstad/multi-worker

deploy:
  edge: true
  provider: elasticbeanstalk
  region: us-east-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-us-east-2-679291916940
  bucket_path: multi-docker
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
